name: Fish_Navigation
channels:
  - conda-forge
  - plotly
  - anaconda
  - defaults
dependencies:
  - python=3.9.7
  - numpy=1.21.2
  - pandas=1.4.1
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cycler=0.11.0
  - docopt=0.6.2
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype
  - future=0.18.2
  - gettext
  - giflib=5.2.1
  - glib=2.68.3
  - glib-tools=2.68.3
  - gmp
  - graphite2=1.3.14
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.4
  - harfbuzz=2.8.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libevent=2.1.10
  - libffi=3.3
  - libglib=2.68.3
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.5
  - libopencv=4.5.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.15.8
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-scalebar=0.8.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - opencv=4.5.2
  - openssl=1.1.1n
  - packaging=21.3
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pipreqs=0.4.10
  - pixman=0.40.0
  - plotly=5.7.0
  - proj=6.2.1
  - py-opencv=4.5.2
  - pycparser=2.21
  - pynmea2=1.18.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyproj=2.6.1.post1
  - pysocks=1.7.1
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2020.1
  - qt=5.12.9
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.37.0
  - tenacity=8.0.1
  - tk=8.6.11
  - tornado=6.1
  - tzdata=2021e
  - urllib3=1.26.7
  - utm=0.7.0
  - wheel=0.37.1
  - x264=1!161.3030
  - xz=5.2.5
  - yarg=0.1.9
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
      - readline
      - nss
      - nspr
      - nettle
      - ncurses
      - libxkbcommon
      - libuuid
      - libunistring
      - libtasn1
      - libstdcxx-ng
      - libidn2
      - libgfortran4
      - libgfortran-ng
      - libgcc-ng
      - libedit
      - gnutls
      - llvmlite==0.36.0
      - matplotlib==3.4.3
